/**
 * ZKP utilities — pure functions for Groth16 proof inputs and signals.
 *
 * Circuits: age-verify, attribute-range, issuer-membership (circuits/).
 *
 * Cryptographic design notes
 * ──────────────────────────
 * SHA-256 ‖ Poseidon Binding (VC commitment layer)
 *   BLOCKID uses a dual-hash construction to bridge the externally anchored
 *   SHA-256 VC fingerprint with the ZK-friendly Poseidon commitment:
 *
 *     vcFingerprint       := SHA-256(canonicalVC JSON)           [bytes32 on-chain]
 *     vcFingerprint_field := toBigInt(vcFingerprint) mod r        [BN254 field element]
 *     vcCommitment        := Poseidon(vcFingerprint_field, secret) [circuit output]
 *
 *   The holder supplies `vcFingerprint_field` as a PUBLIC input to the circuit.
 *   The circuit enforces `vcCommitment = Poseidon(vcFingerprint, secret)` as a
 *   hard constraint, so:
 *     1. A proof can only be generated by a holder who knows the private `secret`
 *        for the specific VC identified by `vcFingerprint`.
 *     2. The on-chain verifier cross-checks `vcFingerprint` against
 *        `CredentialRegistry.isValid(bytes32(vcFingerprint))`, ensuring the VC
 *        is live and not revoked.
 *     3. The VC's actual payload (birthdate, attribute values, etc.) is never
 *        revealed to the verifier.
 *
 * Nullifier generation
 *   Each circuit computes its nullifier INSIDE the arithmetic circuit using
 *   Poseidon, which is algebraically native to BN254 (~240 constraints for
 *   2 inputs; ~280 for 3 inputs). The nullifier is a PUBLIC output signal:
 *     1. It is committed to inside the proof — cannot be forged without the
 *        private secret.
 *     2. A verifier burns the nullifier on-chain (ZKPVerifier.sol) to prevent
 *        replay attacks.
 *     3. Domain separation (scope) ensures a proof accepted by verifier A
 *        cannot be replayed at verifier B.
 *
 *   Previous versions computed the nullifier off-circuit using Keccak-256.
 *   That approach is INSECURE: the nullifier was not bound to the circuit
 *   witness — an attacker could fabricate a fresh nullifier without the secret.
 *
 * Public signal layouts (post SHA-256∥Poseidon binding)
 * ────────────────────────────────
 * IMPORTANT — circom orders public signals OUTPUTS FIRST, then public inputs.
 * snarkjs `groth16.fullProve` therefore returns publicSignals as:
 *
 *   age-verify (9):
 *     [0]=vcCommitment  [1]=nullifier  [2]=referenceTimestamp
 *     [3]=minAgeSeconds [4]=scope      [5]=challenge
 *     [6]=vcFingerprintHi [7]=vcFingerprintLo [8]=holderCommitment
 *   attribute-range (9):
 *     [0]=vcCommitment  [1]=nullifier  [2]=minValue   [3]=maxValue
 *     [4]=scope         [5]=challenge  [6]=vcFingerprintHi
 *     [7]=vcFingerprintLo [8]=holderCommitment
 *   issuer-membership (8):
 *     [0]=vcCommitment  [1]=nullifier  [2]=root      [3]=scope
 *     [4]=challenge     [5]=vcFingerprintHi [6]=vcFingerprintLo
 *     [7]=holderCommitment
 *
 *   ⇒ vcCommitment is ALWAYS at index 0 and nullifier ALWAYS at index 1.
 *   ⇒ ZKPVerifier.sol burns pubSignals[1] for replay protection.
 *   ⇒ Public inputs always follow, in the order declared in `main {public ...}`.
 *
 * Use the PUBLIC_SIGNAL_LAYOUT / extractSignal helpers instead of hard-coded
 * magic indices whenever you need to read a specific signal.
 *
 * Off-chain Merkle tree (issuer-membership)
 *   Use circomlibjs `buildPoseidon()` to build trees compatible with the
 *   on-circuit Poseidon(2) node hasher:
 *     const poseidon = await buildPoseidon();
 *     const nodeHash = (l, r) => poseidon.F.toObject(poseidon([l, r]));
 *   Leaf hashes should be keccak256(issuerId) mod r (field-reduced) OR
 *   Poseidon([issuerId]) for full algebraic consistency.
 */

import { keccak256, toUtf8Bytes, toBigInt } from "ethers";

/** BN254 scalar field r — all witness values must be < r */
export const SNARK_SCALAR_FIELD =
  21888242871839275222246405745257275088548364400416034343698204186575808495617n;

export type CircuitName = "age-verify" | "attribute-range" | "issuer-membership";

export const CIRCUIT_IDS: Record<CircuitName, string> = {
  "age-verify": "age-verify",
  "attribute-range": "attribute-range",
  "issuer-membership": "issuer-membership",
};

/**
 * Full snarkjs public-signal layout per circuit, in the EXACT order returned
 * by `groth16.fullProve`. Circom emits the main component's OUTPUTS first,
 * then its public inputs (in `main {public [...]}` order).
 *
 * Verified against real proofs (2026-09): outputs occupy indices 0..1.
 */
export const PUBLIC_SIGNAL_LAYOUT: Record<CircuitName, readonly string[]> = {
  "age-verify": [
    "vcCommitment", "nullifier",
    "referenceTimestamp", "minAgeSeconds", "scope", "challenge",
    "vcFingerprintHi", "vcFingerprintLo", "holderCommitment",
  ],
  "attribute-range": [
    "vcCommitment", "nullifier",
    "minValue", "maxValue", "scope", "challenge",
    "vcFingerprintHi", "vcFingerprintLo", "holderCommitment",
  ],
  "issuer-membership": [
    "vcCommitment", "nullifier",
    "root", "scope", "challenge",
    "vcFingerprintHi", "vcFingerprintLo", "holderCommitment",
  ],
};

/** Index of a named public signal in `groth16.fullProve` output, per circuit. */
export function publicSignalIndex(
  circuit: CircuitName,
  name: string
): number {
  const layout = PUBLIC_SIGNAL_LAYOUT[circuit];
  const idx = layout.indexOf(name);
  if (idx === -1) throw new Error(`Unknown public signal "${name}" for ${circuit}`);
  return idx;
}

/** Read a named public signal from a raw snarkjs `publicSignals` array. */
export function extractPublicSignal(
  circuit: CircuitName,
  name: string,
  publicSignals: readonly string[]
): string {
  const idx = publicSignalIndex(circuit, name);
  if (idx >= publicSignals.length) {
    throw new Error(`${circuit} publicSignals has length ${publicSignals.length}, expected ≥ ${idx + 1}`);
  }
  return publicSignals[idx];
}

/** Acceptable public-signal array length for a circuit (guards against layout drift). */
export function publicSignalCount(circuit: CircuitName): number {
  return PUBLIC_SIGNAL_LAYOUT[circuit].length;
}

/** True when a proof's public-signal array matches the expected layout length. */
export function isExpectedSignalCount(circuit: CircuitName, publicSignals: readonly string[]): boolean {
  return publicSignals.length === publicSignalCount(circuit);
}

/** Field-compatible numeric value: JS number or BigInt. */
export type FieldValue = number | bigint;

/** Inputs for the age-verify circuit. */
export interface AgeProofInput {
  birthTimestamp: FieldValue;
  referenceTimestamp: FieldValue;
  minAgeSeconds: FieldValue;
  /**
   * SHA-256(canonicalVC JSON) as a 0x-prefixed hex string (bytes32).
   * Split into Hi/Lo 128-bit halves internally — no mod-r loss.
   * Optional: defaults to the zero hash when omitted (backwards-compat shims).
   */
  vcFingerprint?: string;
  /**
   * Poseidon(secret) registered in CredentialRegistry at issuance time.
   * Enforces holder binding inside the circuit: only the holder who knows
   * the secret that hashes to this value can generate a valid proof.
   * Optional: defaults to 0 when omitted (backwards-compat shims — no binding).
   */
  holderCommitment?: string;
}

/** Inputs for the attribute-range circuit. */
export interface AttributeRangeInput {
  value: FieldValue;
  minValue: FieldValue;
  maxValue: FieldValue;
  /** SHA-256(canonicalVC JSON) bytes32 hex. Optional for backwards-compat. */
  vcFingerprint?: string;
  /** Poseidon(secret) from CredentialRegistry. Optional for backwards-compat. */
  holderCommitment?: string;
}

/** Inputs for the issuer-membership circuit. */
export interface IssuerMembershipInput {
  leaf: bigint | string;
  root: bigint | string;
  scope: bigint | string;
  secret: bigint | string;
  pathElements: (bigint | string)[];
  pathIndices: (0 | 1)[];
  /** SHA-256(canonicalVC JSON) bytes32 hex. Optional for backwards-compat. */
  vcFingerprint?: string;
  /** Poseidon(secret) from CredentialRegistry. Optional for backwards-compat. */
  holderCommitment?: string;
}

function assertField(value: number | bigint, name: string): bigint {
  const v = BigInt(value);
  if (v < 0n) throw new Error(`${name} must be non-negative`);
  if (v >= SNARK_SCALAR_FIELD) throw new Error(`${name} exceeds the BN254 scalar field`);
  return v;
}

/** Seconds in a Julian year used for age thresholds. */
export const SECONDS_PER_YEAR = 31_557_600n;

/** Default age threshold: 18 years in seconds. */
export function defaultMinAgeSeconds(years = 18): bigint {
  return BigInt(years) * SECONDS_PER_YEAR;
}

/**
 * Canonical zero placeholder for optional fields (backwards-compat shims).
 * When vcFingerprint is omitted, both halves are 0.
 * When holderCommitment is omitted, the circuit receives 0 (no binding enforced).
 */
const ZERO_VC_FINGERPRINT = "0x" + "00".repeat(32);
const ZERO_HOLDER_COMMITMENT = "0";

/**
 * Split a SHA-256 VC fingerprint (bytes32 hex) into two 128-bit BN254 field
 * elements — one for the upper 16 bytes, one for the lower 16 bytes.
 *
 * Motivation: SHA-256 produces 256 bits; the BN254 scalar field r ≈ 2^254.
 * A naive `raw mod r` loses ≈2 bits and introduces minor collisions.
 * Splitting at the midpoint avoids reduction entirely — each 128-bit half
 * is well within the field — and preserves the full SHA-256 output.
 *
 * Returns: [vcFingerprintHi, vcFingerprintLo]
 *   vcFingerprintHi = uint128(h[0..15])  — upper 16 bytes as a field element
 *   vcFingerprintLo = uint128(h[16..31]) — lower 16 bytes as a field element
 *
 * On-chain reconstruction:
 *   bytes32 fp = bytes32((uint256(vcFingerprintHi) << 128) | vcFingerprintLo);
 *   CredentialRegistry.isValid(fp)  ← validates live VC
 */
export function vcFingerprintToFieldPair(fingerprintHex: string): [bigint, bigint] {
  const hex = fingerprintHex.startsWith("0x") ? fingerprintHex.slice(2) : fingerprintHex;
  if (hex.length !== 64) {
    throw new Error(`vcFingerprint must be a 32-byte hex string (got ${hex.length / 2} bytes)`);
  }
  const hi = BigInt("0x" + hex.slice(0, 32));  // upper 16 bytes — no reduction needed
  const lo = BigInt("0x" + hex.slice(32));       // lower 16 bytes — no reduction needed
  return [hi, lo];
}

/**
 * Legacy single-field conversion — kept for the backwards-compat shims.
 * Prefer vcFingerprintToFieldPair for new circuit calls.
 * @deprecated Use vcFingerprintToFieldPair instead.
 */
export function vcFingerprintToField(fingerprintHex: string): bigint {
  const hex = fingerprintHex.startsWith("0x") ? fingerprintHex.slice(2) : fingerprintHex;
  if (hex.length !== 64) throw new Error(`vcFingerprint must be a 32-byte hex string (got ${hex.length / 2} bytes)`);
  return BigInt("0x" + hex) % SNARK_SCALAR_FIELD;
}

/**
 * Build the snarkjs-compatible circuit input object for age-verify.
 *
 * Returns `expectedPublicSignals` = the deterministic public INPUTS only
 * (7 entries), in the order they appear AFTER the two circuit outputs:
 *
 *   snarkjs publicSignals (9): [vcCommitment(0), nullifier(1),
 *     referenceTimestamp(2), minAgeSeconds(3), scope(4), challenge(5),
 *     vcFingerprintHi(6), vcFingerprintLo(7), holderCommitment(8)]
 *
 * @param input           Age proof inputs.
 * @param secret          Holder's random secret (reduced to BN254 field internally).
 * @param scope           Persistent verifier domain tag.
 * @param challenge       Fresh per-session nonce from the verifier (prevents replay).
 */
export function buildAgeVerifyInputs(
  input: AgeProofInput,
  secret: string,
  scope: string,
  challenge: string = "0"
): {
  circuitInputs: Record<string, string>;
  expectedPublicSignals: string[];
  isAdult: boolean;
} {
  const birth = assertField(input.birthTimestamp, "birthTimestamp");
  const reference = assertField(input.referenceTimestamp, "referenceTimestamp");
  const minAge = assertField(input.minAgeSeconds, "minAgeSeconds");
  const scopeField = fieldFromString(scope);
  const secretField = fieldFromString(secret);
  const challengeField = fieldFromString(challenge);
  const [vcFpHi, vcFpLo] = vcFingerprintToFieldPair(input.vcFingerprint ?? ZERO_VC_FINGERPRINT);
  const hcField = BigInt(input.holderCommitment ?? ZERO_HOLDER_COMMITMENT);

  const isAdult = reference - birth >= minAge;
  return {
    circuitInputs: {
      birthTimestamp:    birth.toString(),
      secret:            secretField.toString(),
      referenceTimestamp: reference.toString(),
      minAgeSeconds:     minAge.toString(),
      scope:             scopeField.toString(),
      challenge:         challengeField.toString(),
      vcFingerprintHi:   vcFpHi.toString(),
      vcFingerprintLo:   vcFpLo.toString(),
      holderCommitment:  hcField.toString(),
    },
    // expectedPublicSignals: deterministic public inputs only.
    // vcCommitment (snarkjs index 0) and nullifier (index 1) are circuit
    // outputs — snarkjs fills them after fullProve. See PUBLIC_SIGNAL_LAYOUT.
    expectedPublicSignals: [
      reference.toString(),
      minAge.toString(),
      scopeField.toString(),
      challengeField.toString(),
      vcFpHi.toString(),
      vcFpLo.toString(),
      hcField.toString(),
      // [7] = vcCommitment — circuit output
      // [8] = nullifier    — circuit output
    ],
    isAdult,
  };
}

/**
 * Build the snarkjs-compatible circuit input object for attribute-range.
 *
 * Returns `expectedPublicSignals` = the deterministic public INPUTS only
 * (7 entries), in the order they appear AFTER the two circuit outputs:
 *
 *   snarkjs publicSignals (9): [vcCommitment(0), nullifier(1),
 *     minValue(2), maxValue(3), scope(4), challenge(5),
 *     vcFingerprintHi(6), vcFingerprintLo(7), holderCommitment(8)]
 *
 * @param input     Attribute range inputs.
 * @param secret    Holder's random secret.
 * @param scope     Persistent verifier domain tag.
 * @param challenge Fresh per-session nonce.
 */
export function buildAttributeRangeInputs(
  input: AttributeRangeInput,
  secret: string,
  scope: string,
  challenge: string = "0"
): {
  circuitInputs: Record<string, string>;
  expectedPublicSignals: string[];
  inRange: boolean;
} {
  const value = assertField(input.value, "value");
  const min = assertField(input.minValue, "minValue");
  const max = assertField(input.maxValue, "maxValue");
  if (min > max) throw new Error("minValue must be <= maxValue");
  const scopeField = fieldFromString(scope);
  const secretField = fieldFromString(secret);
  const challengeField = fieldFromString(challenge);
  const [vcFpHi, vcFpLo] = vcFingerprintToFieldPair(input.vcFingerprint ?? ZERO_VC_FINGERPRINT);
  const hcField = BigInt(input.holderCommitment ?? ZERO_HOLDER_COMMITMENT);

  const inRange = value >= min && value <= max;
  return {
    circuitInputs: {
      value:            value.toString(),
      secret:           secretField.toString(),
      minValue:         min.toString(),
      maxValue:         max.toString(),
      scope:            scopeField.toString(),
      challenge:        challengeField.toString(),
      vcFingerprintHi:  vcFpHi.toString(),
      vcFingerprintLo:  vcFpLo.toString(),
      holderCommitment: hcField.toString(),
    },
    expectedPublicSignals: [
      min.toString(),
      max.toString(),
      scopeField.toString(),
      challengeField.toString(),
      vcFpHi.toString(),
      vcFpLo.toString(),
      hcField.toString(),
      // [7] = vcCommitment
      // [8] = nullifier
    ],
    inRange,
  };
}

/**
 * Build the snarkjs-compatible circuit input object for issuer-membership.
 *
 * Returns `expectedPublicSignals` = the deterministic public INPUTS only
 * (6 entries), in the order they appear AFTER the two circuit outputs:
 *
 *   snarkjs publicSignals (8): [vcCommitment(0), nullifier(1),
 *     root(2), scope(3), challenge(4),
 *     vcFingerprintHi(5), vcFingerprintLo(6), holderCommitment(7)]
 *
 * @param input     Issuer membership inputs.
 * @param challenge Fresh per-session nonce.
 */
function toFieldInput(val: bigint | string, name: string): bigint {
  if (typeof val === "bigint") return assertField(val, name);
  if (typeof val === "string") {
    if (/^(0x[0-9a-fA-F]+|\d+)$/.test(val)) {
      return assertField(BigInt(val), name);
    }
    return fieldFromString(val);
  }
  return assertField(BigInt(val), name);
}

export function buildIssuerMembershipInputs(
  input: IssuerMembershipInput,
  challenge: string = "0"
): {
  circuitInputs: Record<string, unknown>;
  expectedPublicSignals: string[];
} {
  const root = toFieldInput(input.root, "root");
  const scope = toFieldInput(input.scope, "scope");
  const leaf = toFieldInput(input.leaf, "leaf");
  const secret = toFieldInput(input.secret, "secret");
  const challengeField = fieldFromString(challenge);
  const [vcFpHi, vcFpLo] = vcFingerprintToFieldPair(input.vcFingerprint ?? ZERO_VC_FINGERPRINT);
  const hcField = BigInt(input.holderCommitment ?? ZERO_HOLDER_COMMITMENT);
  validateMerklePath(input.pathElements, input.pathIndices, ISSUER_TREE_DEPTH);

  return {
    circuitInputs: {
      leaf:             leaf.toString(),
      secret:           secret.toString(),
      pathElements:     input.pathElements.map(String),
      pathIndices:      input.pathIndices.map(Number),
      root:             root.toString(),
      scope:            scope.toString(),
      challenge:        challengeField.toString(),
      vcFingerprintHi:  vcFpHi.toString(),
      vcFingerprintLo:  vcFpLo.toString(),
      holderCommitment: hcField.toString(),
    },
    expectedPublicSignals: [
      root.toString(),
      scope.toString(),
      challengeField.toString(),
      vcFpHi.toString(),
      vcFpLo.toString(),
      hcField.toString(),
      // [6] = vcCommitment
      // [7] = nullifier
    ],
  };
}

/** Validate a Merkle path shape for issuer-membership. */
export function validateMerklePath(
  pathElements: unknown[],
  pathIndices: unknown[],
  depth: number
): void {
  if (pathElements.length !== depth) throw new Error(`pathElements must have length ${depth}`);
  if (pathIndices.length !== depth) throw new Error(`pathIndices must have length ${depth}`);
  for (let i = 0; i < depth; i++) {
    const idx = Number(pathIndices[i]);
    if (idx !== 0 && idx !== 1) throw new Error(`pathIndices[${i}] must be 0 or 1`);
    assertField(BigInt(pathElements[i] as string), `pathElements[${i}]`);
  }
}

/** DEPTH used by circuits/issuer-membership.circom */
export const ISSUER_TREE_DEPTH = 20;

/** Compute the Merkle tree leaf index implied by pathIndices (LSB-first). */
export function pathIndicesToLeafIndex(pathIndices: (0 | 1)[]): number {
  return pathIndices.reduce((acc, bit, level) => acc + bit * 2 ** level, 0);
}

/**
 * Reduce an arbitrary string to a BN254 scalar field element.
 *
 * This is used to convert human-readable scope/secret strings into field
 * elements suitable for Poseidon inputs:
 *   fieldFromString(s) = keccak256(s) mod r
 *
 * Note: The actual nullifier Poseidon hash is computed inside the Circom
 * circuit. This function is used by the TypeScript layer to derive the field
 * element that will be fed as the `secret` or `scope` circuit input.
 */
export function fieldFromString(s: string): bigint {
  const digest = keccak256(toUtf8Bytes(s));
  return toBigInt(digest) % SNARK_SCALAR_FIELD;
}

/**
 * @deprecated Use circuit-bound Poseidon nullifiers via buildAgeVerifyInputs,
 * buildAttributeRangeInputs, or buildIssuerMembershipInputs instead.
 *
 * This function computed the nullifier off-circuit using Keccak-256, which
 * meant the nullifier was NOT bound to the circuit witness. A prover could
 * fabricate a fresh nullifier without possessing the private secret.
 *
 * Kept here for migration purposes only. Remove once all callsites are
 * updated to use circuit-extracted publicSignals[last] as the nullifier.
 */
export function computeNullifier_DEPRECATED(
  secret: string,
  scope: string,
  circuitId: string = "blockid"
): string {
  const digest = keccak256(toUtf8Bytes(`${circuitId}:${scope}:${secret}`));
  return (toBigInt(digest) % SNARK_SCALAR_FIELD).toString();
}

// Keep the old name exported for backwards compatibility with test imports
// (tests will be updated separately).
export const computeNullifier = computeNullifier_DEPRECATED;

// ── Backwards-compatible signal builders (wraps new builders) ──────────────
// The old buildAgeVerifySignals / buildAttributeRangeSignals APIs returned
// { privateInputs, publicInputs, isAdult/inRange }. Existing code that calls
// these is updated in zkp.service.ts; these shims remain until that migration
// is confirmed complete.

export function buildAgeVerifySignals(input: AgeProofInput): {
  privateInputs: string[];
  publicInputs: string[];
  isAdult: boolean;
} {
  const birth = assertField(input.birthTimestamp, "birthTimestamp");
  const reference = assertField(input.referenceTimestamp, "referenceTimestamp");
  const minAge = assertField(input.minAgeSeconds, "minAgeSeconds");
  const isAdult = reference - birth >= minAge;
  return {
    privateInputs: [birth.toString()],
    publicInputs: [reference.toString(), minAge.toString()],
    isAdult,
  };
}

export function buildAttributeRangeSignals(input: AttributeRangeInput): {
  privateInputs: string[];
  publicInputs: string[];
  inRange: boolean;
} {
  const value = assertField(input.value, "value");
  const min = assertField(input.minValue, "minValue");
  const max = assertField(input.maxValue, "maxValue");
  if (min > max) throw new Error("minValue must be <= maxValue");
  const inRange = value >= min && value <= max;
  return {
    privateInputs: [value.toString()],
    publicInputs: [min.toString(), max.toString()],
    inRange,
  };
}

/** Pack a Groth16 proof into the calldata layout expected by ZKPVerifier.sol */
export interface Groth16ProofJson {
  pi_a: [string, string, string];
  pi_b: [[string, string], [string, string], string];
  pi_c: [string, string, string];
  protocol?: string;
  curve?: string;
}

export interface ZKPCalldata {
  a: [string, string];
  b: [[string, string], [string, string]];
  c: [string, string];
}

/** Convert snarkjs proof JSON to the fixed-size arrays ZKPVerifier.Proof expects. */
export function toVerifierCalldata(proof: Groth16ProofJson): ZKPCalldata {
  return {
    a: [proof.pi_a[0], proof.pi_a[1]],
    // snarkjs G2 points are [x.im, x.re] pairs — already the on-chain order
    b: [
      [proof.pi_b[0][0], proof.pi_b[0][1]],
      [proof.pi_b[1][0], proof.pi_b[1][1]],
    ],
    c: [proof.pi_c[0], proof.pi_c[1]],
  };
}

/** Validate that a snarkjs proof has the expected structural shape. */
export function isValidProofShape(proof: unknown): proof is Groth16ProofJson {
  if (typeof proof !== "object" || proof === null) return false;
  const p = proof as Record<string, unknown>;
  if (!Array.isArray(p.pi_a) || p.pi_a.length < 2) return false;
  if (!Array.isArray(p.pi_b) || p.pi_b.length < 2) return false;
  if (!Array.isArray(p.pi_b[0]) || p.pi_b[0].length < 2) return false;
  if (!Array.isArray(p.pi_b[1]) || p.pi_b[1].length < 2) return false;
  if (!Array.isArray(p.pi_c) || p.pi_c.length < 2) return false;
  return true;
}
