project_id = "gqsiirtclckqnftcglaq"

[functions.issue-credential]
verify_jwt = false

[functions.verify-credential]
verify_jwt = false

[functions.resolve-did]
verify_jwt = false

[functions.oid4vci]
verify_jwt = false

[functions.oid4vp]
verify_jwt = false

[functions.anchor-credential]
verify_jwt = false

[functions.anchor-credential-server]
verify_jwt = false

[functions.admin-users]
verify_jwt = false
