import { useState, useCallback, useEffect, useRef } from "react";
import { supabase } from "@/integrations/supabase/client";
import { useToast } from "@/hooks/use-toast";
import { AMOY_CHAIN_ID_HEX, AMOY_NETWORK } from "@/services/blockchain/config";

interface EthereumProvider {
  isMetaMask?: boolean;
  request: (args: { method: string; params?: any[] }) => Promise<any>;
  on: (event: string, handler: (...args: any[]) => void) => void;
  removeListener: (event: string, handler: (...args: any[]) => void) => void;
}

interface UseWeb3WalletOptions {
  onConnected?: () => void;
}

declare global {
  interface Window {
    ethereum?: EthereumProvider;
  }
}

const SEPOLIA_CHAIN_ID = AMOY_CHAIN_ID_HEX;
const SEPOLIA_NETWORK = AMOY_NETWORK;

export function useWeb3Wallet(
  userId: string | undefined,
  options: UseWeb3WalletOptions = {},
) {
  const { onConnected } = options;
  const [walletAddress, setWalletAddress] = useState<string | null>(null);
  const [isConnecting, setIsConnecting] = useState(false);
  const [chainId, setChainId] = useState<string | null>(null);
  const [isAutoGeneratingDid, setIsAutoGeneratingDid] = useState(false);
  const { toast } = useToast();
  const didGeneratedRef = useRef(false);

  const isMetaMaskInstalled =
    typeof window !== "undefined" && !!window.ethereum?.isMetaMask;
  const isSepoliaNetwork = chainId === SEPOLIA_CHAIN_ID;
  const isPolygonNetwork = isSepoliaNetwork;

  useEffect(() => {
    if (!userId) return;
    supabase
      .from("profiles")
      .select("wallet_address, did")
      .eq("user_id", userId)
      .single()
      .then(({ data }) => {
        if (data?.wallet_address) setWalletAddress(data.wallet_address);
        if (data?.did) didGeneratedRef.current = true;
      });
  }, [userId]);

  useEffect(() => {
    if (!window.ethereum) return;
    const handleAccountsChanged = (accounts: string[]) => {
      if (accounts.length === 0) {
        setWalletAddress(null);
        didGeneratedRef.current = false;
      }
    };
    const handleChainChanged = (id: string) => setChainId(id);
    window.ethereum.on("accountsChanged", handleAccountsChanged);
    window.ethereum.on("chainChanged", handleChainChanged);
    window.ethereum
      .request({ method: "eth_chainId" })
      .then(setChainId)
      .catch(() => {});
    return () => {
      window.ethereum?.removeListener("accountsChanged", handleAccountsChanged);
      window.ethereum?.removeListener("chainChanged", handleChainChanged);
    };
  }, []);

  const switchToSepolia = useCallback(async () => {
    if (!window.ethereum) return;
    try {
      await window.ethereum.request({
        method: "wallet_switchEthereumChain",
        params: [{ chainId: SEPOLIA_CHAIN_ID }],
      });
    } catch (err: any) {
      if (err.code === 4902) {
        await window.ethereum.request({
          method: "wallet_addEthereumChain",
          params: [SEPOLIA_NETWORK],
        });
      }
    }
  }, []);

  const switchToPolygon = switchToSepolia;

  const autoGenerateDid = useCallback(
    async (userId: string) => {
      if (didGeneratedRef.current || isAutoGeneratingDid) return;
      setIsAutoGeneratingDid(true);
      try {
        const { data, error } = await supabase.rpc("generate_did", {
          _user_id: userId,
        });
        if (error) throw error;
        if (data) {
          didGeneratedRef.current = true;
          toast({
            title: "DID Generated",
            description: `Your decentralized identifier has been created from your wallet.`,
          });
        }
      } catch (err: any) {
        toast({
          title: "DID Generation Failed",
          description: err.message,
          variant: "destructive",
        });
      } finally {
        setIsAutoGeneratingDid(false);
      }
    },
    [isAutoGeneratingDid, toast],
  );

  const connectWallet = useCallback(async () => {
    if (!window.ethereum) {
      toast({
        title: "MetaMask not found",
        description: "Please install MetaMask browser extension.",
        variant: "destructive",
      });
      return;
    }
    setIsConnecting(true);
    try {
      const accounts: string[] = await window.ethereum.request({
        method: "eth_requestAccounts",
      });
      if (!accounts.length) throw new Error("No accounts returned");

      const address = accounts[0];
      await switchToSepolia();

      if (userId) {
        const { error } = await supabase
          .from("profiles")
          .update({ wallet_address: address } as any)
          .eq("user_id", userId);
        if (error) throw error;
      }

      setWalletAddress(address);
      didGeneratedRef.current = false;
      toast({
        title: "Wallet Connected",
        description: `Linked ${address.substring(0, 6)}...${address.substring(38)} on Ethereum Sepolia`,
      });

      if (userId) {
        await autoGenerateDid(userId);
      }

      onConnected?.();
    } catch (err: any) {
      toast({
        title: "Connection failed",
        description: err.message || "Could not connect wallet",
        variant: "destructive",
      });
    } finally {
      setIsConnecting(false);
    }
  }, [userId, switchToSepolia, toast, autoGenerateDid]);

  const disconnectWallet = useCallback(async () => {
    if (userId) {
      await supabase
        .from("profiles")
        .update({ wallet_address: null } as any)
        .eq("user_id", userId);
    }
    setWalletAddress(null);
    didGeneratedRef.current = false;
    toast({ title: "Wallet disconnected" });
  }, [userId, toast]);

  const signMessage = useCallback(
    async (message: string): Promise<string | null> => {
      if (!window.ethereum || !walletAddress) return null;
      try {
        const signature = await window.ethereum.request({
          method: "personal_sign",
          params: [message, walletAddress],
        });
        return signature;
      } catch {
        toast({ title: "Signing rejected", variant: "destructive" });
        return null;
      }
    },
    [walletAddress, toast],
  );

  return {
    walletAddress,
    isConnecting,
    isMetaMaskInstalled,
    isPolygonNetwork,
    isAutoGeneratingDid,
    connectWallet,
    disconnectWallet,
    signMessage,
    switchToPolygon,
  };
}
